# This is a useful tool to fetch london station data
# the readme already contains all instructions here and more,
# but this one clarifies the sources and dependencies a bit more,
# so it can be easier to understand
version: '3'

method:
  timestamp

tasks:
  # {{{ fetch london station data
  fetch_london_lines:
    cmds:
      - curl "https://api.tfl.gov.uk/Line/Mode/tube/Route" > tube_lines.json
    dir:
      data/london_trains/lines
    generates:
      - data/london_trains/lines/tube_lines.json

  fetch_london_stations:
    deps:
      - fetch_london_lines
    cmds:
      - jq '.[].id' tube_lines.json > line_ids.txt
    dir:
      data/london_trains/lines
    sources:
      - data/london_trains/lines/tube_lines.json
    generates:
      - data/london_trains/lines/line_ids.txt

  build_london_stoppoints:
    deps:
      - fetch_london_stations
    cmds:
      - python python/london stations/get_stations.py
    sources:
      - python/london stations/get_stations.py
      - data/london_trains/lines/line_ids.txt
    generates:
      - data/london_trains/stoppoints by line/*.csv

  build_london_station_coords:
    deps:
      - build_london_stoppoints
    cmds:
      - python python/london stations/station_coords.py
    sources:
      - python/london stations/station_coords.py
      - data/london_trains/lines/line_ids.txt
      - data/london_trains/stoppoints by line/*.csv
    generates:
      - data/london_trains/stations/station_coords.csv

  # }}}

  # {{{ fetch tokyo station data (TODO)

  #fetch_tokyo_stations:
  #  cmds:
  #    - curl -X GET https://api.odpt.org/api/v4/odpt:Station?acl:consumerKey=$CONSUMERKEY

  # }}}

  clip_london:
    cmds:
      - cargo build --release --bin clip_pp
      - target/release/clip_pp london > ../data/london_pp.csv
    dir: rust
    sources:
      - rust/src/bin/clip_pp.rs
    generates:
      - data/london.csv

  clip_tokyo:
    cmds:
      - cargo build --release --bin clip_pp
      - target/release/clip_pp tokyo > ../data/tokyo_pp.csv
    dir: rust
    sources:
      - rust/src/bin/clip_pp.rs
    generates:
      - data/tokyo.csv
